// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/collector.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 注册响应
type RegisterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CollectInterval int64                  `protobuf:"varint,3,opt,name=collect_interval,json=collectInterval,proto3" json:"collect_interval,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetCollectInterval() int64 {
	if x != nil {
		return x.CollectInterval
	}
	return 0
}

// 指标上报请求
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Cpu           *CPUMetrics            `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryMetrics         `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk          *DiskMetrics           `protobuf:"bytes,5,opt,name=disk,proto3" json:"disk,omitempty"`
	Network       *NetworkMetrics        `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	Gpu           *GPUMetrics            `protobuf:"bytes,7,opt,name=gpu,proto3" json:"gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *MetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsRequest) GetCpu() *CPUMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *MetricsRequest) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *MetricsRequest) GetDisk() *DiskMetrics {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *MetricsRequest) GetNetwork() *NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *MetricsRequest) GetGpu() *GPUMetrics {
	if x != nil {
		return x.Gpu
	}
	return nil
}

// CPU指标
type CPUMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent  float64                `protobuf:"fixed64,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	LoadAvg_1     float64                `protobuf:"fixed64,2,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	LoadAvg_5     float64                `protobuf:"fixed64,3,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`
	LoadAvg_15    float64                `protobuf:"fixed64,4,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`
	CoreCount     int32                  `protobuf:"varint,5,opt,name=core_count,json=coreCount,proto3" json:"core_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUMetrics) Reset() {
	*x = CPUMetrics{}
	mi := &file_proto_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUMetrics) ProtoMessage() {}

func (x *CPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUMetrics.ProtoReflect.Descriptor instead.
func (*CPUMetrics) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{3}
}

func (x *CPUMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *CPUMetrics) GetLoadAvg_1() float64 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *CPUMetrics) GetLoadAvg_5() float64 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *CPUMetrics) GetLoadAvg_15() float64 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *CPUMetrics) GetCoreCount() int32 {
	if x != nil {
		return x.CoreCount
	}
	return 0
}

// 内存指标
type MemoryMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,4,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	Available     uint64                 `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_proto_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryMetrics) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryMetrics) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemoryMetrics) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *MemoryMetrics) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *MemoryMetrics) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

// 磁盘指标
type DiskMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*PartitionMetrics    `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_proto_collector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{5}
}

func (x *DiskMetrics) GetPartitions() []*PartitionMetrics {
	if x != nil {
		return x.Partitions
	}
	return nil
}

// 分区指标
type PartitionMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Mountpoint    string                 `protobuf:"bytes,2,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Fstype        string                 `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	Total         uint64                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,6,opt,name=free,proto3" json:"free,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,7,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionMetrics) Reset() {
	*x = PartitionMetrics{}
	mi := &file_proto_collector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMetrics) ProtoMessage() {}

func (x *PartitionMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionMetrics.ProtoReflect.Descriptor instead.
func (*PartitionMetrics) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{6}
}

func (x *PartitionMetrics) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *PartitionMetrics) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *PartitionMetrics) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *PartitionMetrics) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PartitionMetrics) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *PartitionMetrics) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *PartitionMetrics) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

// 网络指标
type NetworkMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*InterfaceMetrics    `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_proto_collector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkMetrics) GetInterfaces() []*InterfaceMetrics {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

// 网卡指标
type InterfaceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     uint64                 `protobuf:"varint,3,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	PacketsSent   uint64                 `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsRecv   uint64                 `protobuf:"varint,5,opt,name=packets_recv,json=packetsRecv,proto3" json:"packets_recv,omitempty"`
	Errin         uint64                 `protobuf:"varint,6,opt,name=errin,proto3" json:"errin,omitempty"`
	Errout        uint64                 `protobuf:"varint,7,opt,name=errout,proto3" json:"errout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceMetrics) Reset() {
	*x = InterfaceMetrics{}
	mi := &file_proto_collector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceMetrics) ProtoMessage() {}

func (x *InterfaceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceMetrics.ProtoReflect.Descriptor instead.
func (*InterfaceMetrics) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{8}
}

func (x *InterfaceMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceMetrics) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *InterfaceMetrics) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *InterfaceMetrics) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *InterfaceMetrics) GetPacketsRecv() uint64 {
	if x != nil {
		return x.PacketsRecv
	}
	return 0
}

func (x *InterfaceMetrics) GetErrin() uint64 {
	if x != nil {
		return x.Errin
	}
	return 0
}

func (x *InterfaceMetrics) GetErrout() uint64 {
	if x != nil {
		return x.Errout
	}
	return 0
}

type GPUMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*GPUDeviceMetrics    `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUMetrics) Reset() {
	*x = GPUMetrics{}
	mi := &file_proto_collector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMetrics) ProtoMessage() {}

func (x *GPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMetrics.ProtoReflect.Descriptor instead.
func (*GPUMetrics) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{9}
}

func (x *GPUMetrics) GetDevices() []*GPUDeviceMetrics {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GPUDeviceMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Index              int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Vendor             string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model              string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Uuid               string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	DriverVersion      string                 `protobuf:"bytes,6,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	UtilizationPercent float64                `protobuf:"fixed64,7,opt,name=utilization_percent,json=utilizationPercent,proto3" json:"utilization_percent,omitempty"`
	MemoryTotal        uint64                 `protobuf:"varint,8,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed         uint64                 `protobuf:"varint,9,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	MemoryUsedPercent  float64                `protobuf:"fixed64,10,opt,name=memory_used_percent,json=memoryUsedPercent,proto3" json:"memory_used_percent,omitempty"`
	Temperature        float64                `protobuf:"fixed64,11,opt,name=temperature,proto3" json:"temperature,omitempty"`
	PowerWatts         float64                `protobuf:"fixed64,12,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	FanSpeedPercent    float64                `protobuf:"fixed64,13,opt,name=fan_speed_percent,json=fanSpeedPercent,proto3" json:"fan_speed_percent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GPUDeviceMetrics) Reset() {
	*x = GPUDeviceMetrics{}
	mi := &file_proto_collector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUDeviceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUDeviceMetrics) ProtoMessage() {}

func (x *GPUDeviceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUDeviceMetrics.ProtoReflect.Descriptor instead.
func (*GPUDeviceMetrics) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{10}
}

func (x *GPUDeviceMetrics) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUDeviceMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUDeviceMetrics) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPUDeviceMetrics) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUDeviceMetrics) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GPUDeviceMetrics) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *GPUDeviceMetrics) GetUtilizationPercent() float64 {
	if x != nil {
		return x.UtilizationPercent
	}
	return 0
}

func (x *GPUDeviceMetrics) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *GPUDeviceMetrics) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *GPUDeviceMetrics) GetMemoryUsedPercent() float64 {
	if x != nil {
		return x.MemoryUsedPercent
	}
	return 0
}

func (x *GPUDeviceMetrics) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GPUDeviceMetrics) GetPowerWatts() float64 {
	if x != nil {
		return x.PowerWatts
	}
	return 0
}

func (x *GPUDeviceMetrics) GetFanSpeedPercent() float64 {
	if x != nil {
		return x.FanSpeedPercent
	}
	return 0
}

// 指标上报响应
type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_collector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{11}
}

func (x *MetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_collector_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_collector_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 进程监控上报请求
type ProcessReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Processes     []*ProcessInfo         `protobuf:"bytes,3,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessReportRequest) Reset() {
	*x = ProcessReportRequest{}
	mi := &file_proto_collector_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessReportRequest) ProtoMessage() {}

func (x *ProcessReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessReportRequest.ProtoReflect.Descriptor instead.
func (*ProcessReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessReportRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ProcessReportRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProcessReportRequest) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

// 进程信息
type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,5,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,6,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	CreateTime    int64                  `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Command       string                 `protobuf:"bytes,9,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_proto_collector_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ProcessInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ProcessInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// 日志上报请求
type LogReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Logs          []*LogEntry            `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogReportRequest) Reset() {
	*x = LogReportRequest{}
	mi := &file_proto_collector_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogReportRequest) ProtoMessage() {}

func (x *LogReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogReportRequest.ProtoReflect.Descriptor instead.
func (*LogReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{16}
}

func (x *LogReportRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *LogReportRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogReportRequest) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

// 日志条目
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`                                                                       // 日志来源（文件路径或服务名）
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`                                                                         // 日志级别（INFO, WARN, ERROR等）
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                     // 日志内容
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                // 日志时间戳
	Tags          map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外标签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_collector_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{17}
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 脚本执行结果上报请求
type ScriptResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ScriptId      string                 `protobuf:"bytes,2,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`       // 脚本ID
	ScriptName    string                 `protobuf:"bytes,3,opt,name=script_name,json=scriptName,proto3" json:"script_name,omitempty"` // 脚本名称
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`                         // 执行是否成功
	Output        string                 `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`                            // 标准输出
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`                              // 错误输出
	ExitCode      int32                  `protobuf:"varint,8,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`       // 退出码
	DurationMs    int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // 执行耗时（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptResultRequest) Reset() {
	*x = ScriptResultRequest{}
	mi := &file_proto_collector_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptResultRequest) ProtoMessage() {}

func (x *ScriptResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptResultRequest.ProtoReflect.Descriptor instead.
func (*ScriptResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{18}
}

func (x *ScriptResultRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ScriptResultRequest) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *ScriptResultRequest) GetScriptName() string {
	if x != nil {
		return x.ScriptName
	}
	return ""
}

func (x *ScriptResultRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ScriptResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScriptResultRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ScriptResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScriptResultRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ScriptResultRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// 服务状态上报请求
type ServiceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Services      []*ServiceInfo         `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatusRequest) Reset() {
	*x = ServiceStatusRequest{}
	mi := &file_proto_collector_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatusRequest) ProtoMessage() {}

func (x *ServiceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatusRequest.ProtoReflect.Descriptor instead.
func (*ServiceStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{19}
}

func (x *ServiceStatusRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ServiceStatusRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ServiceStatusRequest) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

// 服务信息
type ServiceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                            // 服务名称
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                        // 状态（running, stopped, failed等）
	Enabled        bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`                                     // 是否开机自启
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                              // 服务描述
	UptimeSeconds  int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`    // 运行时长（秒）
	Port           int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`                                           // 服务端口（可选，用于端口检查）
	PortAccessible bool                   `protobuf:"varint,7,opt,name=port_accessible,json=portAccessible,proto3" json:"port_accessible,omitempty"` // 端口是否可访问（可选，用于端口检查结果）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_collector_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_collector_proto_rawDescGZIP(), []int{20}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServiceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ServiceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceInfo) GetPortAccessible() bool {
	if x != nil {
		return x.PortAccessible
	}
	return false
}

var File_proto_collector_proto protoreflect.FileDescriptor

const file_proto_collector_proto_rawDesc = "" +
	"\n" +
	"\x15proto/collector.proto\x12\tcollector\"\xed\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x128\n" +
	"\x04tags\x18\x06 \x03(\v2$.collector.RegisterRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10collect_interval\x18\x03 \x01(\x03R\x0fcollectInterval\"\xac\x02\n" +
	"\x0eMetricsRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12'\n" +
	"\x03cpu\x18\x03 \x01(\v2\x15.collector.CPUMetricsR\x03cpu\x120\n" +
	"\x06memory\x18\x04 \x01(\v2\x18.collector.MemoryMetricsR\x06memory\x12*\n" +
	"\x04disk\x18\x05 \x01(\v2\x16.collector.DiskMetricsR\x04disk\x123\n" +
	"\anetwork\x18\x06 \x01(\v2\x19.collector.NetworkMetricsR\anetwork\x12'\n" +
	"\x03gpu\x18\a \x01(\v2\x15.collector.GPUMetricsR\x03gpu\"\xac\x01\n" +
	"\n" +
	"CPUMetrics\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x01R\fusagePercent\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\x02 \x01(\x01R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\x03 \x01(\x01R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\x04 \x01(\x01R\tloadAvg15\x12\x1d\n" +
	"\n" +
	"core_count\x18\x05 \x01(\x05R\tcoreCount\"\x8e\x01\n" +
	"\rMemoryMetrics\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x04R\x04free\x12!\n" +
	"\fused_percent\x18\x04 \x01(\x01R\vusedPercent\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\x04R\tavailable\"J\n" +
	"\vDiskMetrics\x12;\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x1b.collector.PartitionMetricsR\n" +
	"partitions\"\xc3\x01\n" +
	"\x10PartitionMetrics\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x02 \x01(\tR\n" +
	"mountpoint\x12\x16\n" +
	"\x06fstype\x18\x03 \x01(\tR\x06fstype\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x05 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x06 \x01(\x04R\x04free\x12!\n" +
	"\fused_percent\x18\a \x01(\x01R\vusedPercent\"M\n" +
	"\x0eNetworkMetrics\x12;\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x1b.collector.InterfaceMetricsR\n" +
	"interfaces\"\xd8\x01\n" +
	"\x10InterfaceMetrics\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x03 \x01(\x04R\tbytesRecv\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x04R\vpacketsSent\x12!\n" +
	"\fpackets_recv\x18\x05 \x01(\x04R\vpacketsRecv\x12\x14\n" +
	"\x05errin\x18\x06 \x01(\x04R\x05errin\x12\x16\n" +
	"\x06errout\x18\a \x01(\x04R\x06errout\"C\n" +
	"\n" +
	"GPUMetrics\x125\n" +
	"\adevices\x18\x01 \x03(\v2\x1b.collector.GPUDeviceMetricsR\adevices\"\xb9\x03\n" +
	"\x10GPUDeviceMetrics\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\x12%\n" +
	"\x0edriver_version\x18\x06 \x01(\tR\rdriverVersion\x12/\n" +
	"\x13utilization_percent\x18\a \x01(\x01R\x12utilizationPercent\x12!\n" +
	"\fmemory_total\x18\b \x01(\x04R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_used\x18\t \x01(\x04R\n" +
	"memoryUsed\x12.\n" +
	"\x13memory_used_percent\x18\n" +
	" \x01(\x01R\x11memoryUsedPercent\x12 \n" +
	"\vtemperature\x18\v \x01(\x01R\vtemperature\x12\x1f\n" +
	"\vpower_watts\x18\f \x01(\x01R\n" +
	"powerWatts\x12*\n" +
	"\x11fan_speed_percent\x18\r \x01(\x01R\x0ffanSpeedPercent\"E\n" +
	"\x0fMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"N\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"\x83\x01\n" +
	"\x14ProcessReportRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x124\n" +
	"\tprocesses\x18\x03 \x03(\v2\x16.collector.ProcessInfoR\tprocesses\"\x85\x02\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x05 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\fmemory_bytes\x18\x06 \x01(\x04R\vmemoryBytes\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x03R\n" +
	"createTime\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x18\n" +
	"\acommand\x18\t \x01(\tR\acommand\"r\n" +
	"\x10LogReportRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12'\n" +
	"\x04logs\x18\x03 \x03(\v2\x13.collector.LogEntryR\x04logs\"\xdc\x01\n" +
	"\bLogEntry\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x121\n" +
	"\x04tags\x18\x05 \x03(\v2\x1d.collector.LogEntry.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x02\n" +
	"\x13ScriptResultRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1b\n" +
	"\tscript_id\x18\x02 \x01(\tR\bscriptId\x12\x1f\n" +
	"\vscript_name\x18\x03 \x01(\tR\n" +
	"scriptName\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x06 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1b\n" +
	"\texit_code\x18\b \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\"\x81\x01\n" +
	"\x14ServiceStatusRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x122\n" +
	"\bservices\x18\x03 \x03(\v2\x16.collector.ServiceInfoR\bservices\"\xd9\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12'\n" +
	"\x0fport_accessible\x18\a \x01(\bR\x0eportAccessible2\xf5\x04\n" +
	"\tCollector\x12H\n" +
	"\rRegisterAgent\x12\x1a.collector.RegisterRequest\x1a\x1b.collector.RegisterResponse\x12F\n" +
	"\rReportMetrics\x12\x19.collector.MetricsRequest\x1a\x1a.collector.MetricsResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.collector.HeartbeatRequest\x1a\x1c.collector.HeartbeatResponse\x12N\n" +
	"\x0fReportProcesses\x12\x1f.collector.ProcessReportRequest\x1a\x1a.collector.MetricsResponse\x12E\n" +
	"\n" +
	"ReportLogs\x12\x1b.collector.LogReportRequest\x1a\x1a.collector.MetricsResponse\x12P\n" +
	"\x12ReportScriptResult\x12\x1e.collector.ScriptResultRequest\x1a\x1a.collector.MetricsResponse\x12R\n" +
	"\x13ReportServiceStatus\x12\x1f.collector.ServiceStatusRequest\x1a\x1a.collector.MetricsResponse\x12Q\n" +
	"\x16ReportDockerContainers\x12\x1b.collector.LogReportRequest\x1a\x1a.collector.MetricsResponseB\x17Z\x15monitor-backend/protob\x06proto3"

var (
	file_proto_collector_proto_rawDescOnce sync.Once
	file_proto_collector_proto_rawDescData []byte
)

func file_proto_collector_proto_rawDescGZIP() []byte {
	file_proto_collector_proto_rawDescOnce.Do(func() {
		file_proto_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_collector_proto_rawDesc), len(file_proto_collector_proto_rawDesc)))
	})
	return file_proto_collector_proto_rawDescData
}

var file_proto_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_collector_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: collector.RegisterRequest
	(*RegisterResponse)(nil),     // 1: collector.RegisterResponse
	(*MetricsRequest)(nil),       // 2: collector.MetricsRequest
	(*CPUMetrics)(nil),           // 3: collector.CPUMetrics
	(*MemoryMetrics)(nil),        // 4: collector.MemoryMetrics
	(*DiskMetrics)(nil),          // 5: collector.DiskMetrics
	(*PartitionMetrics)(nil),     // 6: collector.PartitionMetrics
	(*NetworkMetrics)(nil),       // 7: collector.NetworkMetrics
	(*InterfaceMetrics)(nil),     // 8: collector.InterfaceMetrics
	(*GPUMetrics)(nil),           // 9: collector.GPUMetrics
	(*GPUDeviceMetrics)(nil),     // 10: collector.GPUDeviceMetrics
	(*MetricsResponse)(nil),      // 11: collector.MetricsResponse
	(*HeartbeatRequest)(nil),     // 12: collector.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 13: collector.HeartbeatResponse
	(*ProcessReportRequest)(nil), // 14: collector.ProcessReportRequest
	(*ProcessInfo)(nil),          // 15: collector.ProcessInfo
	(*LogReportRequest)(nil),     // 16: collector.LogReportRequest
	(*LogEntry)(nil),             // 17: collector.LogEntry
	(*ScriptResultRequest)(nil),  // 18: collector.ScriptResultRequest
	(*ServiceStatusRequest)(nil), // 19: collector.ServiceStatusRequest
	(*ServiceInfo)(nil),          // 20: collector.ServiceInfo
	nil,                          // 21: collector.RegisterRequest.TagsEntry
	nil,                          // 22: collector.LogEntry.TagsEntry
}
var file_proto_collector_proto_depIdxs = []int32{
	21, // 0: collector.RegisterRequest.tags:type_name -> collector.RegisterRequest.TagsEntry
	3,  // 1: collector.MetricsRequest.cpu:type_name -> collector.CPUMetrics
	4,  // 2: collector.MetricsRequest.memory:type_name -> collector.MemoryMetrics
	5,  // 3: collector.MetricsRequest.disk:type_name -> collector.DiskMetrics
	7,  // 4: collector.MetricsRequest.network:type_name -> collector.NetworkMetrics
	9,  // 5: collector.MetricsRequest.gpu:type_name -> collector.GPUMetrics
	6,  // 6: collector.DiskMetrics.partitions:type_name -> collector.PartitionMetrics
	8,  // 7: collector.NetworkMetrics.interfaces:type_name -> collector.InterfaceMetrics
	10, // 8: collector.GPUMetrics.devices:type_name -> collector.GPUDeviceMetrics
	15, // 9: collector.ProcessReportRequest.processes:type_name -> collector.ProcessInfo
	17, // 10: collector.LogReportRequest.logs:type_name -> collector.LogEntry
	22, // 11: collector.LogEntry.tags:type_name -> collector.LogEntry.TagsEntry
	20, // 12: collector.ServiceStatusRequest.services:type_name -> collector.ServiceInfo
	0,  // 13: collector.Collector.RegisterAgent:input_type -> collector.RegisterRequest
	2,  // 14: collector.Collector.ReportMetrics:input_type -> collector.MetricsRequest
	12, // 15: collector.Collector.Heartbeat:input_type -> collector.HeartbeatRequest
	14, // 16: collector.Collector.ReportProcesses:input_type -> collector.ProcessReportRequest
	16, // 17: collector.Collector.ReportLogs:input_type -> collector.LogReportRequest
	18, // 18: collector.Collector.ReportScriptResult:input_type -> collector.ScriptResultRequest
	19, // 19: collector.Collector.ReportServiceStatus:input_type -> collector.ServiceStatusRequest
	16, // 20: collector.Collector.ReportDockerContainers:input_type -> collector.LogReportRequest
	1,  // 21: collector.Collector.RegisterAgent:output_type -> collector.RegisterResponse
	11, // 22: collector.Collector.ReportMetrics:output_type -> collector.MetricsResponse
	13, // 23: collector.Collector.Heartbeat:output_type -> collector.HeartbeatResponse
	11, // 24: collector.Collector.ReportProcesses:output_type -> collector.MetricsResponse
	11, // 25: collector.Collector.ReportLogs:output_type -> collector.MetricsResponse
	11, // 26: collector.Collector.ReportScriptResult:output_type -> collector.MetricsResponse
	11, // 27: collector.Collector.ReportServiceStatus:output_type -> collector.MetricsResponse
	11, // 28: collector.Collector.ReportDockerContainers:output_type -> collector.MetricsResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_collector_proto_init() }
func file_proto_collector_proto_init() {
	if File_proto_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_collector_proto_rawDesc), len(file_proto_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_collector_proto_goTypes,
		DependencyIndexes: file_proto_collector_proto_depIdxs,
		MessageInfos:      file_proto_collector_proto_msgTypes,
	}.Build()
	File_proto_collector_proto = out.File
	file_proto_collector_proto_goTypes = nil
	file_proto_collector_proto_depIdxs = nil
}
